services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/backend:${GIT_HASH}
    ports:
      - "8000:8000"

  backend-lts:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/backend:lts
    ports:
      - "8000:8000"