FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

# package.json과 package-lock.json만 먼저 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 나머지 소스 코드 복사
COPY . .

# Next.js 빌드
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]