// import { ProjectType } from "@/types/projectType";
// import { delay } from "@/utils/delay";

// export async function getProjects(): Promise<ProjectType[]> {
//   await delay(1000);
//   return [
//     {
//       project_id: 1,
//       user_id: 1,
//       project_name: "AI Vision Project",
//       model_name: "vgg19_bn",
//       description: "컴퓨터 비전 기반 이미지 분류 프로젝트",
//       department: "AI연구소",
//       is_private: false,
//       created_at: "2024-10-31T04:00:42",
//       updated_at: "2024-10-31T04:00:42",
//     },
//     {
//       project_id: 2,
//       user_id: 2,
//       project_name: "Natural Language Processing",
//       model_name: "bert",
//       description: "자연어 처리 프로젝트",
//       department: "NLP팀",
//       is_private: true,
//       created_at: "2024-09-15T08:30:00",
//       updated_at: "2024-09-15T08:30:00",
//     },
//     {
//       project_id: 3,
//       user_id: 3,
//       project_name: "Speech Recognition",
//       model_name: "deepspeech",
//       description: "음성 인식 프로젝트",
//       department: "음성팀",
//       is_private: false,
//       created_at: "2024-08-20T12:45:30",
//       updated_at: "2024-08-20T12:45:30",
//     },
//     {
//       project_id: 4,
//       user_id: 4,
//       project_name: "Recommendation System",
//       model_name: "collaborative_filtering",
//       description: "추천 시스템 프로젝트",
//       department: "추천팀",
//       is_private: true,
//       created_at: "2024-07-10T09:20:15",
//       updated_at: "2024-07-10T09:20:15",
//     },
//     {
//       project_id: 5,
//       user_id: 5,
//       project_name: "Image Generation",
//       model_name: "gan",
//       description: "이미지 생성 프로젝트",
//       department: "생성팀",
//       is_private: false,
//       created_at: "2024-06-05T14:10:50",
//       updated_at: "2024-06-05T14:10:50",
//     },
//     {
//       project_id: 6,
//       user_id: 6,
//       project_name: "Autonomous Driving",
//       model_name: "yolo",
//       description: "자율 주행 프로젝트",
//       department: "자율주행팀",
//       is_private: true,
//       created_at: "2024-05-25T16:30:00",
//       updated_at: "2024-05-25T16:30:00",
//     },
//     {
//       project_id: 7,
//       user_id: 7,
//       project_name: "Medical Imaging",
//       model_name: "unet",
//       description: "의료 영상 분석 프로젝트",
//       department: "의료팀",
//       is_private: false,
//       created_at: "2024-04-15T11:45:20",
//       updated_at: "2024-04-15T11:45:20",
//     },
//     {
//       project_id: 8,
//       user_id: 8,
//       project_name: "Financial Forecasting",
//       model_name: "lstm",
//       description: "금융 예측 프로젝트",
//       department: "금융팀",
//       is_private: true,
//       created_at: "2024-03-10T10:00:00",
//       updated_at: "2024-03-10T10:00:00",
//     },
//     {
//       project_id: 9,
//       user_id: 9,
//       project_name: "Chatbot Development",
//       model_name: "gpt-3",
//       description: "챗봇 개발 프로젝트",
//       department: "챗봇팀",
//       is_private: false,
//       created_at: "2024-02-05T13:20:30",
//       updated_at: "2024-02-05T13:20:30",
//     },
//     {
//       project_id: 10,
//       user_id: 10,
//       project_name: "Sentiment Analysis",
//       model_name: "roberta",
//       description: "감정 분석 프로젝트",
//       department: "감정팀",
//       is_private: true,
//       created_at: "2024-01-01T09:00:00",
//       updated_at: "2024-01-01T09:00:00",
//     },
//   ];
// }
