version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: jingluv/s108:lts
    restart: always
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    volumes:
      - /fastapi/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000